"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1500
format = '''$directory$character'''
palette = 'catppuccin_mocha'
right_format = '''$all'''

[character]
error_symbol = '[󰅂](bold red)'
success_symbol = '[󰅂](bold green)'

[cmd_duration]
format = ' \(󱤦 [$duration]($style)\)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style)'
read_only = '󰍁 '

[directory.substitutions]
'libs/shared' = 'shared'
'services/document-generation' = 'dga'
'services/health-care-provider' = 'hcp'
'services/patient-with-diabetes' = 'pwd'

[docker_context]
format = ' [$symbol$context]($style)'
symbol = ' '

[git_branch]
format = ' [$symbol$branch(:$remote_branch)]($style)'
style = 'bold peach'
symbol = '󰘬 '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
deleted = '✕'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = ' ([\[$all_status$ahead_behind\]]($style))'
modified = '±'
stashed = '❋'

[nodejs]
format = ' [$symbol($version)]($style)'
symbol = ' '

[python]
format = ' [${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'
symbol = '󰌠 '

[terraform]
format = ' [$symbol$workspace]($style)'


[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
